(1) Add negative verifier test utf 8 encoding
w3c/vc-di-bbs-test-suite pull request #32
Opened 2024-06-19 16:11 UTC by aljones15

Adds a test for the [base proof UTF-8 only string encoding normative statement](https://w3c.github.io/vc-di-bbs/#serializebaseproofvalue:~:text=Whenever%20this%20algorithm%20encodes%20strings%2C%20it%20MUST%20use%20UTF%2D8%20encoding.)

Uses [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)
Uses [Reflect](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect)

2024-06-21 15:36 UTC, aljones15 commented
> Looks like this PR also includes #34, it makes it difficult to see what belongs to this PR

I retargeted the PR at 34 so that should remove the 34 commits, sadly the reason for 34 was to make refactors to setup done in 2 separate PRs one common set of refactors. That resulted in one commit in this PR which has a name that suggests it does something similar to PR 34, so if you want me to I can rename the last commit in this PR as PR 34 now does the setup refactoring.

2024-06-25 00:21 UTC, TallTed requested changes

2024-06-25 00:21 UTC, TallTed commented on tests/vc-generator/generators.js
> +          // use `multisign` if provided, otherwise use CBOR
```suggestion
          // use `multisign` if provided; otherwise, use CBOR
```

2024-06-25 00:21 UTC, TallTed commented on tests/vc-generator/generators.js
> +      // if a stub is not found return the original property
```suggestion
      // if a stub is not found, return the original property
```

2024-06-26 22:26 UTC, Wind4Greg approved these changes

2024-06-27 13:23 UTC, aljones15 commented
@TallTed only thing blocking this PR from hitting main and expanding bbs test coverage is your re-review.

2024-06-27 17:09 UTC, TallTed approved these changes

2024-06-27 20:00 UTC, merged