Unset proof type cryptosuite
w3c/vc-di-bbs-test-suite pull request #35
Opened 2024-06-21 15:08 UTC by aljones15

Features:

1. adds a new function to stub methods on an object.
2. stubs `createVerifyData` so that canonize can be done unsafely

2024-06-21 15:43 UTC, PatStLouis commented
#36 says `The proof options MUST contain a type identifier for the cryptographic suite (type) and MAY contain a cryptosuite identifier (cryptosuite).`

Is this meant to overwrite that statement? If so, how does this affect the overwriting of the function `noProofTypeOrCryptosuite` with `allowUnsafeCanonize` from PR #36 ?

2024-06-25 00:24 UTC, TallTed requested changes

2024-06-25 00:24 UTC, TallTed commented on tests/setup.js
> +    // add a generator to turns safe mode off for proof cannonize and hash
```suggestion
    // add a generator to turn safe mode off for proof, canonize, and hash
```

2024-06-25 00:24 UTC, TallTed commented on tests/suites/verify.js
> +        'as output.', async function() {
The `proof options` is being deleted somewhere else...

2024-06-26 22:24 UTC, Wind4Greg approved these changes

2024-06-27 17:11 UTC, TallTed approved these changes

2024-06-27 20:23 UTC, merged