Add test for optional cryptosuite value.
w3c/vc-di-bbs-test-suite pull request #36
Opened 2024-06-21 15:27 UTC by aljones15

2024-06-21 15:35 UTC, PatStLouis commented on tests/suites/verify.js
> +              disclosed?.invalid?.noProofTypeOrCryptosuite),
should this be changed to  `disclosed?.invalid?.allowUnsafeCanonize` ? Same for all appearances of `noProofTypeOrCryptosuite` such as on line 116?

2024-06-21 15:55 UTC, PatStLouis commented on tests/suites/verify.js
> +              disclosed?.invalid?.noProofTypeOrCryptosuite),
thanks for clarifying!

2024-06-21 15:55 UTC, PatStLouis approved these changes

2024-06-25 00:26 UTC, TallTed requested changes

2024-06-25 00:26 UTC, TallTed commented on tests/setup.js
> +    // add a generator to turns safe mode off for proof canonize and hash
```suggestion
    // add a generator to turn safe mode off for proof, canonize, and hash
```

2024-06-26 22:23 UTC, Wind4Greg approved these changes

2024-06-27 17:11 UTC, TallTed approved these changes

2024-06-27 21:28 UTC, merged