Replace verifyData with stubVerifyData.
w3c/vc-di-bbs-test-suite pull request #37
Opened 2024-06-21 20:26 UTC by aljones15

Adds the ability to stubVerifyData which makes the stub useful for multiple different tests such as invalid created, invalid hmac, etc.

2024-06-25 00:28 UTC, TallTed requested changes

2024-06-25 00:28 UTC, TallTed commented on tests/vc-generator/mockMethods.js
> +    // used for tests that need created to be in the proof
```suggestion
    // used for tests that need `created` to be in the proof
```

2024-06-26 22:21 UTC, Wind4Greg approved these changes

2024-06-27 17:12 UTC, TallTed approved these changes

2024-06-27 21:40 UTC, merged