(5) Invalid hmac test
w3c/vc-di-bbs-test-suite pull request #38
Opened 2024-06-26 13:04 UTC by aljones15

Adds a test for this statement: _Per the recommendations of [[RFC2104](https://w3c.github.io/vc-di-bbs/#bib-rfc2104)], the HMAC key MUST be the same length as the digest size; for SHA-256, this is 256 bits or 32 bytes._

Features:
1. a new test for invalid hmac
2. better naming for the stub generators (previous PRs conflated mock and stub)
3. support for stubbing derive

2024-06-26 22:19 UTC, Wind4Greg approved these changes

2024-06-27 17:19 UTC, TallTed requested changes
editorial, human-facing, grammar in comments

2024-06-27 17:19 UTC, TallTed commented on tests/assertions.js
> +    `Expected hmacKey length to be ${keyLength} received: ${hmacKey.length}`);
```suggestion
    `Expected hmacKey length to be ${keyLength}. Received: ${hmacKey.length}.`);
```

2024-06-27 17:19 UTC, TallTed commented on tests/vc-generator/stubMethods.js
> +    // to encode `data` for `sign`
```suggestion
    // encode `data` for `sign` using `multisign` if provided; 
    // otherwise, using CBOR
```

2024-06-27 17:19 UTC, TallTed commented on tests/vc-generator/stubMethods.js
> +  // should created by deleted?
```suggestion
  // should created be deleted?
```

2024-06-27 17:19 UTC, TallTed commented on tests/vc-generator/stubMethods.js
> +    // 2. Ensure mandatory and / or selective data will be disclosed.
```suggestion
    // 2. Ensure mandatory and/or selective data will be disclosed.
```

2024-06-27 17:19 UTC, TallTed commented on tests/vc-generator/stubMethods.js
> +    // the non-mandatory messages as these are the indexes used in BBS.
```suggestion
    // the non-mandatory messages, as these are the indexes used in BBS.
```

2024-06-28 15:27 UTC, aljones15 commented
@TallTed awaiting you re-review on this one.

2024-07-01 19:53 UTC, TallTed approved these changes

2024-07-01 20:09 UTC, merged